# Generated by Django 3.0 on 2020-02-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=50)),
                ('job_address', models.CharField(max_length=50)),
                ('contact_number', models.FloatField(max_length=15)),
                ('jobs_description', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
