# Generated by Django 3.0 on 2020-02-13 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='jobs_deadline',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='jobs_qualification',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='jobs_salary',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
