# Generated by Django 3.0 on 2020-02-13 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20200213_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='jobs_deadline',
        ),
    ]
