# Generated by Django 3.0 on 2020-02-13 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_jobs_jobs_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='jobs_qualification',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='jobs_salary',
        ),
    ]
